#!/usr/bin/env bash
# Buat deploy/.env.production dari .env lokal + domain HTTPS
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_LOKAL="${ROOT}/.env"
ENV_PROD="${ROOT}/deploy/.env.production"

if [[ ! -f "${ENV_LOKAL}" ]]; then
  echo "GAGAL: .env belum ada — salin dari .env.example dan isi MONGODB_URI"
  exit 1
fi

# Baca nilai dari .env tanpa source (aman untuk karakter khusus di URI)
ambil_var() {
  local kunci="$1"
  grep -E "^${kunci}=" "${ENV_LOKAL}" | head -1 | cut -d= -f2- | tr -d '\r' || true
}

DOMAIN="${1:-$(ambil_var WARGIO_PUBLIC_URL)}"
if [[ -z "${DOMAIN}" ]]; then
  read -r -p "Domain HTTPS production (contoh https://wargio.domain.com): " DOMAIN
fi
DOMAIN="${DOMAIN%/}"

MONGODB_URI="$(ambil_var MONGODB_URI)"
if [[ -z "${MONGODB_URI}" ]]; then
  echo "GAGAL: MONGODB_URI kosong di .env"
  exit 1
fi

MONGODB_DATABASE="$(ambil_var MONGODB_DATABASE)"
RATE_LIMIT="$(ambil_var RATE_LIMIT_PER_MINUTE)"
GEMINI_API_KEY="$(ambil_var GEMINI_API_KEY)"
GEMINI_MODEL="$(ambil_var GEMINI_MODEL)"
GOOGLE_CLOUD_PROJECT="$(ambil_var GOOGLE_CLOUD_PROJECT)"
GOOGLE_CLOUD_LOCATION="$(ambil_var GOOGLE_CLOUD_LOCATION)"
AGENT_ENGINE_ID="$(ambil_var AGENT_ENGINE_ID)"

mkdir -p "${ROOT}/deploy"
cat > "${ENV_PROD}" <<EOF
# Generated by scripts/siapkan_env_production.sh — JANGAN commit

WARGIO_PUBLIC_URL=${DOMAIN}
MONGODB_URI=${MONGODB_URI}
MONGODB_DATABASE=${MONGODB_DATABASE:-wargio_demo}

MCP_LIVE_ENABLED=false
RATE_LIMIT_PER_MINUTE=${RATE_LIMIT:-30}
CORS_ORIGINS=${DOMAIN}

GEMINI_API_KEY=${GEMINI_API_KEY}
GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION:-us-central1}
AGENT_ENGINE_ID=${AGENT_ENGINE_ID}

NEXT_PUBLIC_API_URL=
EOF

echo "OK: ${ENV_PROD} dibuat"
echo "   WARGIO_PUBLIC_URL=${DOMAIN}"
echo "   MCP_LIVE_ENABLED=false (UI cepat di production)"
if [[ -z "${GEMINI_API_KEY}" ]]; then
  echo "   PERINGATAN: GEMINI_API_KEY kosong — chat pakai regex fallback di VPS"
  echo "   (ADC gcloud tidak tersedia di dalam container Docker)"
fi
